title: Voeg een CSS-class toe
hero_image: images/banner.png
description: Maak een nieuwe CSS-class en pas deze toe op HTML-elementen.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Voeg een CSS-class toe

