title: Add a CSS class
hero_image: images/banner.png
description: Create a new CSS class and apply it to HTML elements. 
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Add a CSS class

