title: Ajouter une classe CSS
hero_image: images/banner.png
description: Crée une nouvelle classe CSS et applique-la aux éléments HTML.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Ajouter une classe CSS

